- src/pyglet/window/cocoa/pyglet_view.py
Scroll direction is reversed in pyglet, in contrast to other applications.
> Correct scroll direction in OS X.

- src/gamepack/thb/cards/equipment.py
- src/gamepack/thb/cards/spellcard.py
场景①：蓝的上家使用了罪袋狂欢，对蓝造成伤害。
场景②：蓝弃置巫女服发动了极智。
场景③：游戏结束。
极智：你的回合外，当有非延时符卡的效果对一名角色生效后，你可以弃置一张牌使该效果对该角色重新进行一次结算，此时效果来源视为你。每轮限一次。
巫女服：装备后：你无法响应【罪袋狂欢】。
结算①：蓝装备有巫女服，无法响应【罪袋狂欢】。
结算②：蓝发动极智，弃置了巫女服，再次结算【罪袋狂欢】。
结算③：蓝没有装备巫女服，可以响应【罪袋狂欢】。
问题：蓝极智之后，仍然无法响应【罪袋狂欢】。
By：木子化十
> 蓝的极智与巫女服的结算

- src/pyglet/window/cocoa/pyglet_view.py
dy need to be translated to window coordinate when dragging,
but should not when scrolling.
> Fix direction of dy on drag.

- src/thb/cards/equipment.py
It is a subtle bug to fix that when Tenshi percept, she can take YinYangOrb regardless of whether the equipment is really detached or not. The fatetelling result must be given after the codes come out of the "with as" transaction which ensures equipment cards are truly detached at the end of using Orb to change fatetell results.
> Request: YinYangOrb fatetell, taken out of card migration

- src/thb/cards/spellcard.py
When Demolition aims at target, it has been judged whether target has any card in 4 card zones; nevertheless, whence target launches Reject which is again rejected, demolition really takes effect at a target with no cards at all, the game collapses. This corner condition is now prevented, once and for all.
> Prevention for Crash by Demolition spellcard

- src/thb/characters/yugi.py
Once Yugi with RepentanceStick launches atk but cancels damage, she will be able to drop 3 cards from the target, which is subtly different from descriptions showing that she can only exert freakingpower to drop cards after real damage is done.
> Request: Add restriction on FreakingPower

- src/thb/characters/parsee.py
In 2017-12 Ver THB real game, Alice may exert DollBlast on Parsee twice if Parsee recycles the DIAMOND equip dropped from Alice, which relates to the card migrated being not yet detached.
> Parsee: detach before Recycle

- src/thb/characters/youmu.py
Consider the situation as follows: Youmu tries to put on a new UFO or suit, replacing the former one, which drops non-weapon equip, then dn+n>=2, (weapon not lost), she will lose necessary vitality. Here cards in dn shall be tested with a bool judging whether any weapons are among them.
>  Adjustment of Youmu's Vatality

- src/thb/characters/rumia.py
Rumia: Fix darkness malfunction
Still working on problems of VC and TreatAs. In aya's skill -> treat_as, block 1 -> 0; in melancholy limit, block all skills, walk all cards; these work well. Rumia shall also block being chosen as tgt of vc with treat_as.
> Rumia: fix KOF Darkness malfunction

- src/thb/cards/equipment.py
It prevents the classmix from being overriden by InevitableAtk; it also takes the kyouko resonance into consideration.
> Roukanken reenable time changed: big change

- src/thb/ui/ui_meta/characters/momiji.py
- src/thb/ui/ui_meta/characters/yukari.py
Consider an instance: Yukari tries to spirit away 2 cards (maybe very valuable equip) of an enemy character, and then she launches Exinwan which results in her fall by herself before finalize stage; however, the 2 cards that are expected to be returned to enemy's cardlist, will be excluded from the game's cardlists forever (2 cards are destroyed). After discussion, users reach a consensus that all right for yukari's powerful skill, but words on skills are too misleading to cope with such situations.
Complaints argue that some descriptions are unfriendly to new users and skill descriptions of Yukari, Momiji are not clear enough so as to let all users evaluate the true strengths and weaknesses of the characters involved. Once I dismissed these complaints, nonetheless, when the situation …
> Clarification of skill: temporary [out of game] cardlist description

- src/thb/cards/spellcard.py
Recently one mad sinsack changed by exinwan from shiki (which directly results the fall of shiki) in KOF triggered a rarely seen bug.
If and only if in KOF, shiki falls within another one's fatetellstage, sinsakck stays in ft zone like it never finished till it succeeds.
Here give a specific "if next == stop and len(pl) == 2" outside while loop: always move it away.
Unstoppable sinsack ft report: http://www.thbattle.net/thread-81153-1-1.html
> Fix bug: Mad Sinsack in KOF

- src/thb/characters/kaguya.py
投诉称，响子和团扇出现时，有时偶发问题。
查client_log发现是辉夜。属于第三方，技能管得太宽。
当时查看不少对照组，凡是辉夜不在，就没有团扇响子问题。
详查得：
是一个鬼故事,当时调查了很久，团扇竟然能让不相干的手牌变成隐藏的洗牌，以至于影响到了辉夜模块和这里的接口（竟然改掉了card的根本属性）
具体出现：
0. 攻击者使用红色弹幕，击伤响子；伤害是使用牌的插入结算。
1. 响子回响了牌。收到自己手牌。
2. 团扇发动，虽然只是针对装备，但本身触发了ShuffleHandler。
3. ShuffleHandler令响子的手牌里，那张牌变成了HiddenCard，一切原牌属性消除。
4. 伤害结算完毕，结算“使用后”（after ActionStageLaunchCard），辉夜对于那张牌计数，校验序列走到if card.category，报错，该牌根本没有这个属性。
具体展开：
equipment.py
```python
equip = user_input([src], ChoosePeerCardInputlet(self, tgt, ['equips']))
```
actions.py：
```python
@register_eh
class ShuffleHandler(EventHandler):
interested = ('action_after', 'action_before', 'action_stage_action', 'card_migration', 'user_input_start')
def handle(self, evt_type, arg):
if evt_type == 'action_stage_action':
self.do_shuffle()
elif evt_type in …
```
> Fix Kyouko+Kaguya bug: add Kaguya's test sequence to protect

- src/thb/characters/medicine.py
- src/thb/characters/rumia.py
According to card description, Rumia's CheatingHandler shall get triggered the same time as ReimuExterminateHandler, and when the two coincide, it has been defined in reimu.py that Rumia's time has higher priority, while actually Rumia's time is later, due to the mistaken code writing "after PlayerTurn" (shall be adjusted to "apply FinalizeStage").
> :bug: Make Rumia CheatingHandler Consistent with description

- src/thb/ui/ui_meta/characters/chen.py
A bug in UI test sequence.
In ui_meta.chen.py, class FlyingSkanda, while testing if chosen rawcard satisfying the conditions, there is a mistake which exposes <error>.
If and Only if choosing a GrazeCard, it shows "ui.ui_meta 错误", which is due to grazecard being the only basic card with None as associated_action.
Old code:
while True:
if c.is_card(cards.AttackCard): break
rst = c.is_card(cards.RejectCard)
rst = rst or c.is_card(cards.DollControlCard)
rst = (not rst) and issubclass(c.associated_action, cards.InstantSpellCardAction)
if rst: break
return (False, u'请选择一张【弹幕】或者除【人形操控】与【好人卡】之外的非延时符卡！')
Here the code gets:
#=======GAME STARTED: 601278=======
#<THBattle2v2 at 0x1996c710>
#>> Player: Tewi:MORIYA [FFEBCD]枫
#>> Player: Nazrin:HAKUREI 樱花味厨娘
#>> Player: Shikieiki:HAKUREI 梦境
#>> …
> Make Chen UI consistent with implementation and prevent showing UI error

- src/thb/characters/alice.py
History Problem of Shinmyoumaru and Alice
\thbattle\src\thb\characters\alice.py , line 269, in handle
if tgt.has_skill(DollBlast):
UnboundLocalError: local variable 'tgt' referenced before assignment
> :bug: Make Alice DollBlast play well after fallen - after test

- src/game/base.py
When an action can_fire() -> True before action, and can_fire() -> False after being interfered by anything like RejectCard, it shows that the LC has no rst to return.
tarting new HTTPS connection (1): api.leancloud.cn
Starting new HTTPS connection (1): api.leancloud.cn
Starting new HTTPS connection (1): api.leancloud.cn
Starting new HTTPS connection (1): api.leancloud.cn
Starting new HTTPS connection (1): api.leancloud.cn
Starting new HTTPS connection (1): api.leancloud.cn
<THBattleIdentity at 0x1ee43530> failed with UnboundLocalError
Traceback (most recent call last):
File "C:\thbattle\Python27\lib\site-packages\gevent\greenlet.py", line 327, in run
result = self._run(*self.args, **self.kwargs)
File "C:\thbattle\src\client\core\game_client.py", line 229, in _run …
> :wrench: Fix LaunchCard return rst for Invalid Actions

- src/thb/characters/youmu.py
Complaints on Dec 4, 2019:
Some players argue that they witness a 3 vitality youmu...
Same problem as the zero vitality one:
Imagine youmu is with 2 weapons already, and then put on a UFO... Vitality Double plus.
Fixed just like the 0 vitality case.
> :bug: Make Youmu Vitality no exceeding two in a single turn

- src/thb/cards/equipment.py
It is an accidental problem because the handler toposorting graph has already made ayaroundfan goes after Reimu, Momiji and so on, however, when it comes to a small game without anything else but only the AyaRoundfan and Dying, A goes prior to D, a local diorder is invoked.
Fix it.
> :bug: Make AyaRoundfan execute after Dying AskingForHeal

- src/thb/characters/medicine.py
Take the former Mokou dead in "before fatetell" using exinwan as an example: medicine shall judge if the character she tried to poison is still alive when processed before the "before fatetell".
> :bug: Ensure Medicine cannot Ciguatera on FatetellStage dead characters

- src/thb/characters/mokou.py
There are records that Mokou is really fallen then use Exinwan to revive (not truly), but then get poisoned by Medicine.
It's a problem in UI with str|se.
> :bug: Make Mokou Reborn play well with Exinwan

- src/thb/ui/ui_meta/characters/ran.py
Disputes occur when HouraiJewel and Ran's EI coincide. Since the HouraiJewel is SpellCardAction but has no SpellCard, and Ran's Handler listens this Action:
``` 
class ExtremeIntelligenceHandler(EventHandler):
interested = ('action_after', 'game_begin')
def handle(self, evt_type, act):
if evt_type == 'action_after' and isinstance(act, InstantSpellCardAction):
if isinstance(act, Reject): return act
g = Game.getgame()
target = g.current_player
```
Also, players are used to using Ran EI to repeat the Jewel's SpellCardAction.
Change the lines (add one word) accordingly.
> :speech_balloon: Fix Ran ExtremeIntelligence lines

- src/thb/cards/equipment.py
Old ver:
```
check(card in tgt.cards) or card in set(tgt.showncards)
```
If check failed then UI report (prompt) words...
Change into:
```
check(card in set(tgt.cards) or card in set(tgt.showncards))
```
> :bug: Fix ScarletRhapsodySkill checking conditions

- src/thb/characters/suika.py
Reports on Jan 27, 2020 say that Suika's DrawCards in advance of ActionStage triggered Devoted unexpectedly. The truth is, in implementation of DevotedHandler, as long as the current player is still the linked partner (here is Keine), Suika is able to let the partner draw cards even if it is turn of herself.
```
if g.current_player is not cp: return act
```
Here if Suika's EventListener is still `elif evt_type == action_apply and isinstance(act, PlayerTurn)`, 
then when she draw cards, the `current_player` is not herself, but her cp instead, which makes the bug. The reason is that `emit event apply` is prior to `apply()` which changes the `g.current_player = p`:
```
class PlayerTurn(GenericAction):
def __init__(self, target):
self.source = self.target = target
self.pending_stages = [ …
```
> :bug: Fix unexpected DrunkenDreamDrawCards triggering DevotedDrawCards

- src/thb/cards/basic.py
With DrunkenDream Handler's time moved to PrepareStage, SoberUp shall also get moved.
```
class DrunkenDreamHandler(EventHandler):
interested = ('action_apply', 'calcdistance')
execute_before = ('WineHandler', )
```
Time between them has been made right before.
(Passed local test)
> :bug: Fix SoberUp time dislocation from DrunkenDream

- src/thb/characters/reimu.py
> Handle 6 Disputes of Order
>> (1, 'LunaticHandler')
>> (2, 'DisarmHandler')
>> (3, 'FreakingPowerHandler')
>> (4, 'NenshaPhoneHandler')
>> (5, 'AyaRoundfanHandler')
>> (6, 'ReimuExterminateHandler')
All 5 comparisons have passed local test.
> :bug: Adjust ReimuExterminate Order after active and weapon skills

- src/thb/characters/kyouko.py
Once Seija's Reversal cancelled the attack and transtyped it into a Duel, Kyouko shall no longer be able to launch a resonanced attack upon Seija.
Passed local test 2v2, no crash.
> :bug: Fix conflict between Resonance and Reversal

- src/thb/characters/sp_satori.py
- src/thb/ui/ui_meta/characters/sp_satori.py
Updating tips:
1. Still using deepcopy to enhance defense from changing names... (qwq)
2. The order changed between ThirdEye and other passive skills' eventListeners;
3. Description changed.
4. Differences between KOF and nonKOF.
P.S.: Youmu handler still undone
> :sparkles: Minor tune of SpSatori

- src/thb/characters/seiga.py
- src/thb/characters/yuyuko.py
It is reported that Seiga and Yuyuko will waste some time if boss is shot down in games.
Also, the real time that Seiga executes her event shall be readjusted according to the description.
Local test passed; no bugs yet.
Also, no rings detected in the TOPOSORT graph:
Type in EventHandlers' Names: (if end, type enter)
Handle 4 Disputes of Order
> (1, 'SummonKOFHandler')
> (2, 'DeathHandler')
> (3, 'PerfectCherryBlossomHandler')
> (4, 'SummonHandler')
(With time goes by, the system shall no longer rely on toposort... this is just a example... when seiga and yuyuko matter on other one's fall and their eventListeners make it coincide)
AkiTributeHandler -> AshesHandler -> AssaultKOFHandler -> AssistedHealHandler -> AssistedUseHandler -> AttackCardRangeHandler -> AttackCardVitalityHandler -> …
> :bug: Solve time delay caused by PerfectCherryBlossom and Summon

- src/settings.py
- src/thb/characters/flandre.py
- src/thb/characters/sp_flandre.py
- src/thb/characters/sp_satori.py
- src/thb/ui/ui_meta/characters/flandre.py
First of all, the event listeners of old skill `CriticalStrike` is wiped out from all files and all event listeners are subordinated into a new order.
Secondly, the `Exterminate` which will be wiped out is remained (but I think only one skill remained may not be appropriate just for now), due to its 25*25 icon and sound effect.
Thirdly, this initial reworked version employs the sound effect of remilia (just one), which shall be wiped out in the future.
Last but not least, local test is passed and no crashes or bugs are detected.
> :sparkles: Flandre reworked

- src/thb/characters/eirin.py
It is obvious that once Eirin tries to heal or help 1 HP characters opposing Shinmyoumaru, a probably fallen character will see the button of heal or draw. This has been prevented, owing to user complaints.
> :bug: Make Eirin SkySilk play well with Shinmyoumaru

- src/thb/characters/flandre.py
- src/thb/characters/koishi.py
- src/thb/characters/sp_satori.py
- src/thb/ui/ui_meta/characters/sp_satori.py
(1) According to the advices of many designers, set a cost of one handcard which prevents SpSatori keep sticking on a very suitable skill and never change (like that in Yukari SpiritingAway almost devoured a whole Yukari, or use her functionalities when having a YoumuPhantom).
(2) Putting the skill switch in free selections at ActionStage will trigger more problems when Aya is to count her cards (to 2), when Yuyuko reduces the life of others then abandon the skill, when Yukari is switched off her SpiritedAway cards may never go back. In fact, according to the descriptions, Yukari or Yuyuko behaves just like the words may predict, but players may complain on these details. Consequentially the trigger is set at "before the PlayerTurn".
(3) Local test detects no crashes or bugs.
> :sparkles: SpSatori ThirdEye event tuned to before PlayerTurn

- src/thb/characters/nitori.py
- src/thb/ui/ui_meta/characters/nitori.py
No local crashes or bugs.
Checking in BusinessLogicLayer and UserInterfaceLayer both to counter tagons.
(PS: I do not like one eventListener listening on multi events especially when the ehs themselves need an incomplete sorting map)
> :bug: Fix Nitori Craftsman double or more launching graze or heal

- src/thb/ui/ui_meta/characters/eirin.py
In fact Medicine can silence the LunaString action stage attack.
In description she should be unable to silence it (in words).
Change descriptions.
> :speech_balloon: Correct LunaString description to TreatAs

- src/thb/characters/koishi.py
- src/thb/ui/ui_meta/characters/koishi.py
说好了的临场又调……亏得它之前还反向查出了`UseCard`的`can_fire()`存在问题并且改过来的说……（现在自然是没有用了，不过把荷取和梅花欣的潜在问题提前解决了）
原因是“防止开局群体符卡后迅速强大”的失衡。
> :sparkles: Koishi slight tune permitting UseCard in Unconsciousness

- src/thb/characters/remilia.py
As is reported among the complaints on a multi-mixed class of action `Attack` which results in a conflict when a user adopts the method of both `RemiliaSpear` and `HouraiJewel` then even a Rejected Jewel attack can cause two HP damage of Wined Spear. The truth is once a Jewel modified spear is chosen to be launched, there is only Jewel effect left.
Also this is a problem on order of events: `chara > equip`.
Modified.
> :bug: Remilia Spear order tuned before HouraiJewel and other weapons

- src/thb/ui/inputs.py
For a long time the UI prompt string of `Morphing` has stayed unable to read in Chinese, for in py ver2 only `u'...'` can show correct words; even though it does not really matter in py ver3 whether it is prefixed with `u` or not, it seems that the old version may have to correct the last mistake of unicode of all strings in order to maintain the coding coordination. (>_<)
> :speech_balloon: Correct Mamizou Morphing UI string to unicode

- src/thb/characters/sp_youmu.py
- src/thb/ui/ui_meta/characters/sp_youmu.py
1) Step up crash prevention and time-wasting prevention under extreme circumstances such as `InsightfulSword` facing `Shinmyoumaru`, as well as `PresentWorldSlash` facing `Exinwan`.
2) Correct mistake of no marking if it is normal graze or virtual graze.
3) Correct mistake of showing repeated lines of `PresentWorld` in game info.
4) Make `Mixin` subclass of `AskForCard` in order to show virtual `UseCard` in game info.
5) Correct order of playing sound as the original `Mixin` class can not play any sound when `UseCard` is processed.
6) Make space for more game info descriptions to fill in the blanks in the future.
To conclude, when it comes to the 4 events below, no crash, right sound effect, and good game info:
UseCard, `GrazeCard`;
UseCard, `InsightfulSwordGrazeCard`;
LaunchCard, …
> :notes: SpYoumu tiny problems fixed

- src/thb/characters/sp_youmu.py
FIrst bug oriented from the classmix. Koishi `Unconscience` encounters with `InsightfulSword` and when it comes to `UseGraze` when responding to `MapCannon`, according to description, Youmu shall not launch weapon to use a virtual graze, however in former implementation code she can. Bug.
To find the reason, the length of Youmu's cardlist is printed, in which the weapon card detached unintentionally, resulting in the length of her handcard list underestimated by 1. When it comes to `AskForCard`, it seems the weapon is detached before calculating wearing it.
As a solution, the weapon selected to be launched is moved back into her handcards after responding to `MapCannon`, before wearing equips.
> :bug: InsightfulSword UseCard detachment restored
